--- # My First YAML playbook
- hosts: 192.168.0.29       
  user: ansiblejan
  sudo: yes              # yes or no
  connection: ssh        # ssh or paramico
  gather_facts: yes       # yes or no
  tasks:
    - name: Install HTTPD server on centos 7
      action: yum name=httpd state=installed
    - name: wait for the service to start listening on port 80
      wait_for:
       path: /tmp/Robin
      
